Upgrade terraform-provider-akamai to v1.12.0
pulumi/pulumi-akamai pull request #93
Opened 2022-04-05 22:28 UTC by jkodroff

Also fixes many missing docs.

Fixes #92

2022-04-05 22:42 UTC, guineveresaenger approved these changes
I believe you that this fixes the docs, but where is the docs folder?

2022-04-05 22:48 UTC, guineveresaenger requested changes
On second thought, l wanted to add:

a) omg yay more docs!

b) can we put the breaking changes into the changelog? not entirely sure how that works with github native releases and goreleaser but I believe there is a way

2022-04-06 15:18 UTC, stack72 approved these changes

2022-04-06 15:20 UTC, jkodroff commented
@guineveresaenger Per @stack72, only the title is included in the release notes. It's incumbent upon me to edit the release notes after the new version is released, which I will do today.

2022-04-06 15:20 UTC, merged